//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfiles_S.A.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int EmpleadoID { get; set; }
        public string Nombres { get; set; }
        public string DPI { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Direccion { get; set; }
        public string NIT { get; set; }
        public Nullable<int> DepartamentoID { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
    }
}
